Numpy 主要支持矩阵操作和运算

Numpy 代码高效是用C编写的

讲解目录：

数组简介和数组的构造（ndarray）

数组取值和赋值

数学运算

broadcasting

逻辑运算

数组高级操作

文件输入输出

课堂小项目：用Numpy写一个Softmax

In [2]:
import numpy as np

一维数组可以看做向量Vector 二维数组可以看做二维矩阵 三维数组 可以看做三维矩阵

使用np.array去初始化一个数组

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
type([1,2,3])

list

In [8]:
a[0] #使用下标取数据

1

In [10]:
a[0]=5 #modify  date
print(a)

[5 2 3]


In [11]:
b=np.array([[1,2,3],[1,2,3]])
print(b)

[[1 2 3]
 [1 2 3]]


In [12]:
type(b)

numpy.ndarray

In [15]:
print(b.shape)

(2, 3)


有一些内置的创建数组的函数

数组可以有不同的数据类型

生成数组可以指定数据类型，如果不指定numpy会自动匹配合适的类型

使用astype赋值数组并转换数据的类型

In [17]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [19]:
print(np.ones((2,5)))

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [21]:
print(np.full((3,4),6))

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [23]:
print(np.eye(6)*6)#对角单位矩阵

[[ 6.  0.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.  0.]
 [ 0.  0.  0.  6.  0.  0.]
 [ 0.  0.  0.  0.  6.  0.]
 [ 0.  0.  0.  0.  0.  6.]]


In [29]:
print(np.random.random((3,4)))

In [34]:
print(np.empty((2,3,3)))

[[[  4.67296746e-307   1.69121096e-306   1.29061074e-306]
  [  1.69119873e-306   1.78019082e-306   8.34441742e-308]
  [  1.78022342e-306   6.23058028e-307   9.79107872e-307]]

 [[  6.89807188e-307   7.56594375e-307   6.23060065e-307]
  [  1.78021527e-306   8.34454050e-308   1.11261027e-306]
  [  1.15706896e-306   1.33512173e-306   3.49698923e-317]]]


In [40]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [39]:
np.arange(15).shape

(15,)

In [43]:
int_array=np.array([1,2,3,4,5])
print(int_array,int_array.dtype)

[1 2 3 4 5] int32


In [45]:
float_arr=int_array.astype(np.float)
print(float_arr,float_arr.dtype)

[ 1.  2.  3.  4.  5.] float64


In [46]:
float_arr=np.array([3.2,4.6,5.1,-3.5])
print(float_arr,float_arr.dtype)

[ 3.2  4.6  5.1 -3.5] float64


In [48]:
int_arr=float_arr.astype(np.int)
print(int_arr,int_arr.dtype)

[ 3  4  5 -3] int32


使用astype将字符串数组  转化为float类型数组

In [52]:
str_arr=np.array(['3.2','3.8','2.6','4.5'])
str_arr

array(['3.2', '3.8', '2.6', '4.5'],
      dtype='<U3')

In [54]:
float_arr=str_arr.astype(np.float)
float_arr

array([ 3.2,  3.8,  2.6,  4.5])

In [56]:
int_arr=np.arange(10)
float_arr=np.array([3.2,5.6])
print(int_arr.dtype,float_arr.dtype)

int32 float64


In [57]:
int_arr.astype(dtype=float_arr.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

array index 取值和赋值

In [59]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [64]:
b=a[0:2,2:]
print(b)

[[3 4]
 [7 8]]


In [65]:
b[0,0]=123
print(a)
print(b)

[[  1   2 123   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[123   4]
 [  7   8]]


In [66]:
print(a)

[[  1   2 123   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [67]:
a[0,2]=3

In [68]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [72]:
col_r1=a[:,2:]
print(col_r1,col_r1.shape)

[[ 3  4]
 [ 7  8]
 [11 12]] (3, 2)


In [74]:
b=np.array([0,2,0,1])
print(b,b.dtype,b.shape)

[0 2 0 1] int32 (4,)


In [75]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [79]:
print(np.arange(3))

[0 1 2]


In [81]:
# a[np.arange(3),b]   #这个有点问题

In [83]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [85]:
bool_index=(a>2)
print(bool_index)

[[False False]
 [ True  True]
 [ True  True]]


In [89]:
print(a[bool_index],a[bool_index].shape)

[3 4 5 6] (4,)


In [90]:
x=np.array([1,2])
y=np.array([1.2,2.4])
z=np.array([1,2],dtype=np.int64)

In [91]:
print(x.dtype,y.dtype,z.dtype)

int32 float64 int64


接下来是数学元素  这将是numpy的重点内容

逐元素求和

逐元素求差

逐元素求积

逐元素求商

In [3]:
x=np.array([[1,2],[3,4]],dtype=float)
y=np.array([[5,6],[7,8]],dtype=float)

In [5]:
print(x,x.shape)
print(y,y.shape)

[[1. 2.]
 [3. 4.]] (2, 2)
[[5. 6.]
 [7. 8.]] (2, 2)


In [6]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [7]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

In [8]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [9]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [10]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [11]:
np.multiply(x,y)

array([[ 5., 12.],
       [21., 32.]])

In [13]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [14]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [15]:
np.sqrt(x)#开根号

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

 matrix multiplication 矩阵乘法

In [19]:
v=np.array([9,10])
w=np.array([10,11])

In [20]:
np.dot(v,w)

200

In [31]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [32]:
print(np.dot(x,v))

[29 67]


In [30]:
print(np.dot(x,y))#矩阵相乘

[[19 22]
 [43 50]]


In [27]:
x.T

array([[1, 3],
       [2, 4]])

In [34]:
arr=np.arange(16).reshape(2,2,4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [35]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [37]:
print(np.sum(x))

10


In [38]:
print(np.sum(x,axis=0))

[4 6]


In [39]:
print(np.sum(x,axis=1))

[3 7]


In [41]:
x_arr=np.array([1.1,1.2,1.3,1.4,1.5])
y_arr=np.array([2.1,2.2,2.3,2.4,2.5])
print(x_arr,y_arr)

[1.1 1.2 1.3 1.4 1.5] [2.1 2.2 2.3 2.4 2.5]


In [42]:
cond=np.array([True,False,True,False,True])

In [43]:
print(np.where(cond,x_arr,y_arr))

[1.1 2.2 1.3 2.4 1.5]


In [44]:
arr=np.array(np.random.randn(4,4))
print(arr)

[[ 0.65100767 -0.06578     0.38355996  0.29512558]
 [-1.00308938  0.14891062 -0.13107127 -0.22002458]
 [-1.47618492 -0.88452781 -0.11381633  0.21620309]
 [-0.38683136  1.80055862  0.28382928 -1.01757834]]


In [45]:
arr>0

array([[ True, False,  True,  True],
       [False,  True, False, False],
       [False, False, False,  True],
       [False,  True,  True, False]])

In [46]:
print(np.where(arr>0,1,-1))

[[ 1 -1  1  1]
 [-1  1 -1 -1]
 [-1 -1 -1  1]
 [-1  1  1 -1]]


In [49]:
print(arr)

[[ 0.65100767 -0.06578     0.38355996  0.29512558]
 [-1.00308938  0.14891062 -0.13107127 -0.22002458]
 [-1.47618492 -0.88452781 -0.11381633  0.21620309]
 [-0.38683136  1.80055862  0.28382928 -1.01757834]]


In [50]:
arr.ravel()#将矩阵拉平

array([ 0.65100767, -0.06578   ,  0.38355996,  0.29512558, -1.00308938,
        0.14891062, -0.13107127, -0.22002458, -1.47618492, -0.88452781,
       -0.11381633,  0.21620309, -0.38683136,  1.80055862,  0.28382928,
       -1.01757834])

In [51]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(arr1)
print()
print(arr2)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]


In [55]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [56]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [58]:
np.vstack((arr1,arr2))#vertical

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [59]:
np.hstack((arr1,arr2))#horizontal

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [63]:
np.c_[1:6,-5:0]#切片直接转为数组

array([[ 1, -5],
       [ 2, -4],
       [ 3, -3],
       [ 4, -2],
       [ 5, -1]])

numpy的文件输入和输出

读取csv文件作为数组

数组文件读写

多个数组文件一起压缩存储

In [65]:
arr=np.loadtxt('array_ex.txt',delimiter=',')
print(arr)

[[ 5.800520e-01  1.867300e-01  1.040717e+00  1.134411e+00]
 [ 1.945630e-01 -6.358100e-01 -9.365840e-01  1.236540e-01]
 [-1.236850e-01  2.685470e-01 -6.985230e-01  4.742800e-02]
 [-1.484413e+00  4.176000e-03 -7.442330e+05  5.487000e-03]
 [ 2.302564e+00  2.003654e-01  1.670236e+00 -1.881090e+00]
 [-1.932300e-01  1.047233e+00  4.828030e-01  9.603340e-01]]


In [67]:
arr=np.arange(50).reshape(2,5,5)
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]
